// content.js — runs in every frame, captures interactions per spec v1.0.0 §3, §4
(() => {
  if (window.__interactionRecorderInjected) return;
  window.__interactionRecorderInjected = true;

  // ---------- config (mirrors spec §12 defaults) ----------
  const CFG = {
    domStableThresholdMs: 500,
    typingDebounceMs: 600,
    selectorIdRejectionPatterns: [
      /^mui-/, /^emotion-/, /^radix-/, /^chakra-/, /^css-/,
      /^MuiBox-/, /^sc-/,
      /^:r[0-9a-z]+:$/,
      /^[a-z0-9]{6,}-[a-z0-9]{6,}$/
    ],
    testIdAttributes: ['data-testid', 'data-test', 'data-cy', 'data-qa', 'data-test-id']
  };

  // ---------- state ----------
  let recording = false;
  let lastActionTime = null;
  let lastMutationTime = null;
  let mutationCountSinceLastAction = 0;
  let mutationObserver = null;
  let typingDebounceTimer = null;
  const typingBuffer = new Map();
  let actionCounter = 0;
  // Per-frame random seed so action ids don't collide across frames within a session
  const FRAME_SEED = Math.random().toString(36).slice(2, 8);

  // ---------- §6.4 auto-generated ID rejection ----------
  function isAutoGeneratedId(id) {
    if (!id) return true;
    return CFG.selectorIdRejectionPatterns.some(rx => rx.test(id));
  }

  function cssEscape(s) {
    return (window.CSS && CSS.escape) ? CSS.escape(s) : String(s).replace(/(["\\])/g, '\\$1');
  }

  function getCssPath(el) {
    if (!el || el.nodeType !== 1) return null;
    const path = [];
    let cur = el;
    while (cur && cur.nodeType === 1 && cur !== document.documentElement) {
      let part = cur.nodeName.toLowerCase();
      if (cur.id && !isAutoGeneratedId(cur.id)) {
        part = `#${cssEscape(cur.id)}`;
        path.unshift(part);
        break;
      }
      let nth = 1, sib = cur;
      while ((sib = sib.previousElementSibling)) {
        if (sib.nodeName === cur.nodeName) nth++;
      }
      part += `:nth-of-type(${nth})`;
      path.unshift(part);
      cur = cur.parentElement;
    }
    return path.join(' > ');
  }

  function getXPath(el) {
    if (!el || el.nodeType !== 1) return null;
    if (el.id && !isAutoGeneratedId(el.id)) return `//*[@id="${el.id}"]`;
    const parts = [];
    let cur = el;
    while (cur && cur.nodeType === 1) {
      let i = 1, sib = cur.previousSibling;
      while (sib) {
        if (sib.nodeType === 1 && sib.nodeName === cur.nodeName) i++;
        sib = sib.previousSibling;
      }
      parts.unshift(`${cur.nodeName.toLowerCase()}[${i}]`);
      cur = cur.parentNode;
      if (!cur || cur.nodeType !== 1) break;
    }
    return '/' + parts.join('/');
  }

  function isUnique(sel) {
    try { return document.querySelectorAll(sel).length === 1; } catch (_) { return false; }
  }

  // §6.2 minimal implicit role mapping
  const IMPLICIT_ROLE = {
    a: (el) => el.hasAttribute('href') ? 'link' : null,
    button: 'button',
    input: (el) => {
      const t = (el.getAttribute('type') || 'text').toLowerCase();
      if (t === 'button' || t === 'submit' || t === 'reset') return 'button';
      if (t === 'checkbox') return 'checkbox';
      if (t === 'radio') return 'radio';
      if (t === 'range') return 'slider';
      return 'textbox';
    },
    textarea: 'textbox',
    select: 'combobox',
    img: 'img',
    nav: 'navigation',
    main: 'main',
    header: 'banner',
    footer: 'contentinfo',
    h1: 'heading', h2: 'heading', h3: 'heading',
    h4: 'heading', h5: 'heading', h6: 'heading'
  };

  function computedRole(el) {
    if (!el || el.nodeType !== 1) return null;
    const explicit = el.getAttribute('role');
    if (explicit) return explicit;
    const tag = el.tagName ? el.tagName.toLowerCase() : null;
    const m = IMPLICIT_ROLE[tag];
    if (typeof m === 'function') return m(el);
    return m || null;
  }

  function accessibleName(el) {
    if (!el || el.nodeType !== 1) return '';
    const labelAttr = el.getAttribute('aria-label');
    if (labelAttr) return labelAttr.trim().slice(0, 120);
    const labelledBy = el.getAttribute('aria-labelledby');
    if (labelledBy) {
      const ids = labelledBy.split(/\s+/).filter(Boolean);
      const text = ids.map(id => {
        const node = document.getElementById(id);
        return node ? (node.innerText || node.textContent || '') : '';
      }).join(' ').trim();
      if (text) return text.slice(0, 120);
    }
    if (el.tagName === 'INPUT' && el.id) {
      try {
        const lab = document.querySelector(`label[for="${cssEscape(el.id)}"]`);
        if (lab) return ((lab.innerText || lab.textContent || '') + '').trim().slice(0, 120);
      } catch (_) {}
    }
    if (el.tagName === 'IMG') return ((el.getAttribute('alt') || '') + '').trim().slice(0, 120);
    const txt = ((el.innerText || el.textContent || '') + '').trim();
    if (txt) return txt.slice(0, 120);
    if ('value' in el && el.value != null) return String(el.value).slice(0, 120);
    return '';
  }

  // Build §3.3 selector bundle.
  function buildSelectorBundle(el) {
    const bundle = {
      primary: null,
      alternatives: [],
      xpath: getXPath(el),
      textContent: ((el.innerText || el.textContent || '') + '').trim().slice(0, 120),
      accessibleName: accessibleName(el),
      tagName: el.tagName ? el.tagName.toLowerCase() : null,
      attributes: {}
    };

    if (!el || el.nodeType !== 1) return bundle;

    const useful = new Set([
      'id', 'class', 'name', 'type', 'role', 'aria-label', 'aria-labelledby',
      'placeholder', 'href', 'value', 'title', 'alt', 'for', 'contenteditable'
    ]);
    for (const attr of el.attributes) {
      if (useful.has(attr.name) || attr.name.startsWith('data-')) {
        bundle.attributes[attr.name] = attr.value;
      }
    }

    const tag = bundle.tagName;
    const seen = new Set();
    const pushAlt = (kind, value) => {
      if (!value) return;
      const key = kind + '|' + value;
      if (seen.has(key)) return;
      seen.add(key);
      bundle.alternatives.push({ kind, value });
    };

    // 1) testid family
    for (const a of CFG.testIdAttributes) {
      if (el.hasAttribute(a)) {
        const v = `[${a}="${cssEscape(el.getAttribute(a))}"]`;
        if (isUnique(v)) pushAlt('testid', v);
      }
    }

    // 2) id (rejecting auto-generated per §6.4)
    if (el.id && !isAutoGeneratedId(el.id)) {
      const v = `#${cssEscape(el.id)}`;
      if (isUnique(v)) pushAlt('id', v);
    }

    // 3) name
    const nameAttr = el.getAttribute('name');
    if (nameAttr) {
      const v = `${tag}[name="${cssEscape(nameAttr)}"]`;
      if (isUnique(v)) pushAlt('name', v);
    }

    // 4) aria-label
    const ariaLabel = el.getAttribute('aria-label');
    if (ariaLabel) {
      const v = `${tag}[aria-label="${cssEscape(ariaLabel)}"]`;
      if (isUnique(v)) pushAlt('aria', v);
    }

    // 5) roleText hint (Playwright-style — not a CSS selector)
    const role = computedRole(el);
    const accName = bundle.accessibleName;
    if (role && accName) {
      pushAlt('roleText', `role=${role} & text="${accName.slice(0, 60)}"`);
    }

    // 6) Full CSS path — always present
    const cssPath = getCssPath(el);
    if (cssPath) pushAlt('css', cssPath);

    // 7) XPath — always present, last resort
    if (bundle.xpath) pushAlt('xpath', bundle.xpath);

    // primary = first CSS-resolvable alternative in rank order; fall back to xpath.
    for (const alt of bundle.alternatives) {
      if (alt.kind === 'roleText' || alt.kind === 'xpath') continue;
      bundle.primary = alt.value;
      break;
    }
    if (!bundle.primary) {
      const xp = bundle.alternatives.find(a => a.kind === 'xpath');
      if (xp) bundle.primary = xp.value;
    }

    return bundle;
  }

  // §3.4 element snapshot
  function elementSnapshot(el) {
    if (!el || el.nodeType !== 1) return null;
    const r = el.getBoundingClientRect();
    let valueSnapshot = null;
    if ('value' in el) {
      valueSnapshot = el.type === 'password' ? '<<password>>' : (el.value == null ? null : String(el.value));
    }
    return {
      tagName: el.tagName ? el.tagName.toLowerCase() : null,
      type: el.type || null,
      innerText: ((el.innerText || '') + '').slice(0, 200),
      boundingRect: { x: r.x, y: r.y, width: r.width, height: r.height },
      isVisible: r.width > 0 && r.height > 0,
      computedRole: computedRole(el),
      isContentEditable: !!(el.isContentEditable),
      valueSnapshot
    };
  }

  function newActionId() {
    actionCounter += 1;
    return `act_${FRAME_SEED}_${actionCounter.toString().padStart(4, '0')}`;
  }

  function recordAction(type, target, extra = {}) {
    if (!recording) return;
    const now = Date.now();
    const msSinceLastAction = lastActionTime != null ? (now - lastActionTime) : null;
    const msSinceLastMutation = lastMutationTime != null ? (now - lastMutationTime) : null;
    const wasDomStable = msSinceLastMutation == null
      ? true
      : msSinceLastMutation >= CFG.domStableThresholdMs;

    const action = {
      id: newActionId(),
      type,
      timestamp: now,
      url: location.href,
      title: document.title,
      // frameId / framePath populated by background on append
      frameId: 0,
      framePath: [],
      selectors: target ? buildSelectorBundle(target) : null,
      element: target ? elementSnapshot(target) : null,
      waitBefore: {
        msSinceLastAction,
        msSinceLastMutation,
        domMutationsObservedSinceLastAction: mutationCountSinceLastAction,
        // Network observations filled by background
        pendingNetworkRequests: 0,
        msSinceLastNetworkActivity: null,
        wasNetworkIdle: false,
        wasDomStable
      },
      annotations: { label: '', comment: '' },
      ...extra
    };
    lastActionTime = now;
    mutationCountSinceLastAction = 0;
    try {
      chrome.runtime.sendMessage({ type: 'recorder:action', action });
    } catch (_) { /* extension context may be reloading */ }
  }

  function startRecording() {
    if (recording) return;
    recording = true;
    lastActionTime = Date.now();
    lastMutationTime = null;
    mutationCountSinceLastAction = 0;

    mutationObserver = new MutationObserver((muts) => {
      mutationCountSinceLastAction += muts.length;
      lastMutationTime = Date.now();
    });
    mutationObserver.observe(document.documentElement, {
      childList: true, subtree: true, attributes: true, characterData: true
    });

    document.addEventListener('click', onClick, true);
    document.addEventListener('change', onChange, true);
    document.addEventListener('input', onInput, true);
    document.addEventListener('submit', onSubmit, true);
    document.addEventListener('keydown', onKeyDown, true);
    document.addEventListener('blur', onBlurFlush, true);

    patchHistory();
    window.addEventListener('popstate', onSpaNav);
    window.addEventListener('hashchange', onSpaNav);

    // Register this frame's <iframe> element selectors with background, for framePath.
    // window.frameElement is non-null for same-origin child frames only.
    try {
      if (window.frameElement) {
        chrome.runtime.sendMessage({
          type: 'recorder:registerFrame',
          frameElementSelectors: buildSelectorBundle(window.frameElement)
        });
      }
    } catch (_) {}

    recordAction('frame:ready', null, { initialUrl: location.href });
  }

  function stopRecording() {
    if (!recording) return;
    flushTypingBuffer();
    recording = false;
    if (mutationObserver) { mutationObserver.disconnect(); mutationObserver = null; }
    document.removeEventListener('click', onClick, true);
    document.removeEventListener('change', onChange, true);
    document.removeEventListener('input', onInput, true);
    document.removeEventListener('submit', onSubmit, true);
    document.removeEventListener('keydown', onKeyDown, true);
    document.removeEventListener('blur', onBlurFlush, true);
    window.removeEventListener('popstate', onSpaNav);
    window.removeEventListener('hashchange', onSpaNav);
  }

  // §4.1
  function onClick(e) {
    if (e.isTrusted === false) return;
    if (e.target && e.target.tagName === 'OPTION') return;
    const detail = e.detail || 1;
    const type = detail >= 2 ? 'dblclick' : 'click';
    recordAction(type, e.target, {
      button: e.button | 0,
      modifiers: { ctrl: !!e.ctrlKey, shift: !!e.shiftKey, alt: !!e.altKey, meta: !!e.metaKey }
    });
  }

  // §4.3
  function onChange(e) {
    const t = e.target;
    if (!t) return;
    let value;
    if (t.type === 'password') value = '<<password>>';
    else if (t.type === 'checkbox' || t.type === 'radio') value = !!t.checked;
    else value = (t.value ?? '');
    recordAction('change', t, { value, inputType: t.type || null });
  }

  // §4.2 — debounced text input
  function onInput(e) {
    const t = e.target;
    if (!t) return;
    typingBuffer.set(t, t.value ?? '');
    clearTimeout(typingDebounceTimer);
    typingDebounceTimer = setTimeout(flushTypingBuffer, CFG.typingDebounceMs);
  }

  function flushTypingBuffer() {
    if (typingBuffer.size === 0) return;
    for (const [el, val] of typingBuffer) {
      const safe = el.type === 'password' ? '<<password>>' : val;
      recordAction('input', el, { value: safe, inputType: el.type || null });
    }
    typingBuffer.clear();
    if (typingDebounceTimer) { clearTimeout(typingDebounceTimer); typingDebounceTimer = null; }
  }

  function onBlurFlush() { flushTypingBuffer(); }

  // §4.4
  function onSubmit(e) {
    flushTypingBuffer();
    recordAction('submit', e.target);
  }

  // §4.5
  const SPECIAL_KEYS = new Set([
    'Enter', 'Escape', 'Tab',
    'ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight',
    'Backspace', 'Delete', 'Home', 'End', 'PageUp', 'PageDown'
  ]);
  function onKeyDown(e) {
    const hasModifier = e.ctrlKey || e.metaKey || e.altKey;
    if (!SPECIAL_KEYS.has(e.key) && !hasModifier) return;
    recordAction('keydown', e.target, {
      key: e.key,
      modifiers: { ctrl: !!e.ctrlKey, shift: !!e.shiftKey, alt: !!e.altKey, meta: !!e.metaKey }
    });
  }

  // §4.7 SPA navigation
  function onSpaNav() {
    recordAction('navigation:spa', null, { newUrl: location.href });
  }

  function patchHistory() {
    if (history.__patchedByRecorder) return;
    history.__patchedByRecorder = true;
    const _push = history.pushState;
    const _replace = history.replaceState;
    history.pushState = function () {
      const ret = _push.apply(this, arguments);
      window.dispatchEvent(new Event('popstate'));
      return ret;
    };
    history.replaceState = function () {
      const ret = _replace.apply(this, arguments);
      window.dispatchEvent(new Event('popstate'));
      return ret;
    };
  }

  // ---------- messaging ----------
  chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
    if (msg?.type === 'recorder:start') { startRecording(); sendResponse({ ok: true }); }
    else if (msg?.type === 'recorder:stop') { stopRecording(); sendResponse({ ok: true }); }
    else if (msg?.type === 'recorder:status') { sendResponse({ recording }); }
    return true;
  });

  // Resume after a page reload mid-session
  chrome.storage.local.get(['recordingActive'], (res) => {
    if (res.recordingActive) startRecording();
  });
})();
